apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: <LB IP>
  selector:
    app: product-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000

