apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
      - name: flask-container
        image: <docker image link>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "<db_user DB_NAME>"
        - name: DB_PASSWORD
          value: "<db password>"
        - name: DB_HOST
          value: "<DB IP>"
        - name: DB_PORT
          value: "<port num - 5432 def>"
        - name: DB_NAME
          value: "<DB_NAME>"
        - name: API_TOKEN
          value: "mysecrettoken123"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

